class Employee:
    def __init__(self):
        self.name
        self.rank
        self.position

        self.monday_hours
        self.monday_lunch
        self.tuesday_hours
        self.tuesday_lunch
        self.wednesday_hours
        self.wednesday_lunch
        self.thursday_hours
        self.thursday_lunch
        self.friday_1a_hours
        self.friday_1a_lunch
        self.friday_1b_hours
        self.friday_1b_lunch
        self.friday_2a_hours
        self.friday_2a_lunch
        self.friday_2b_hours
        self.friday_2b_lunch
        self.friday_3a_hours
        self.friday_3a_lunch
        self.friday_3b_hours
        self.friday_3b_lunch
        self.saturday_1a_hours
        self.saturday_1a_lunch
        self.saturday_1b_hours
        self.saturday_1b_lunch
        self.saturday_2a_hours
        self.saturday_2a_lunch
        self.saturday_2b_hours
        self.saturday_2b_lunch
        self.saturday_3a_hours
        self.saturday_3a_lunch
        self.saturday_3b_hours
        self.saturday_3b_lunch
        self.sunday_1
        self.sunday_2
        self.sunday_3

        self.hours = [
            self.monday_hours,
            self.monday_lunch,
            self.tuesday_hours,
            self.tuesday_lunch,
            self.wednesday_hours,
            self.wednesday_lunch,
            self.thursday_hours,
            self.thursday_lunch,
            self.friday_1a_hours,
            self.friday_1a_lunch,
            self.friday_1b_hours,
            self.friday_1b_lunch,
            self.friday_2a_hours,
            self.friday_2a_lunch,
            self.friday_2b_hours,
            self.friday_2b_lunch,
            self.friday_3a_hours,
            self.friday_3a_lunch,
            self.friday_3b_hours,
            self.friday_3b_lunch,
            self.saturday_1a_hours,
            self.saturday_1a_lunch,
            self.saturday_1b_hours,
            self.saturday_1b_lunch,
            self.saturday_2a_hours,
            self.saturday_2a_lunch,
            self.saturday_2b_hours,
            self.saturday_2b_lunch,
            self.saturday_3a_hours,
            self.saturday_3a_lunch,
            self.saturday_3b_hours,
            self.saturday_3b_lunch,
            self.sunday_1,
            self.sunday_2,
            self.sunday_3,
        ]
    
    def string_to_hours(self):
        print(self.hours[0])